### PR TITLE
integration suite test helper to assert API supports sidecars

### PR DESCRIPTION
**Pull request by drnic**
Sidecars added in https://github.com/cloudfoundry/capi-release/releases/tag/1.79.0
* CC API Version: 2.134.0 and 3.69.0

Example usage:

```go
var _ = Describe("Rubyapp Integration Test", func() {
	var app *cutlass.App
	BeforeEach(func() {
		Expect(ApiHasSidecar()).To(BeTrue())
	})
```

### CODE REVIEW

**Comment by chhhavi** [comment]
Hi @drnic 
Thanks for making this PR, I was wondering why did you want to make this particular change?

**Comment by drnic** [comment]
@chhhavi my buildpack packages a sidecar and the test suite assumes the target CF can support sidecars, so I put in an assertion upfront:

https://github.com/starkandwayne/etcdproxy-buildpack/blob/d4a7ce73dd890d1187970a00e06bea368aac74f0/src/etcdproxy/integration/rubyapp_test.go#L14-L16

Is this a good/bad idea? I saw the other two similar assertion helpers (`ApiHasTask`, `ApiHasMultiBuildpack`) and followed the pattern. Sorry if I'm misunderstanding the pattern here.

**Comment by sclevine** [comment]
Given that the CAPI feature to support buildpack-contributed sidecar start commands is planned but hasn't been released yet, I wonder if we should wait for that CAPI version before merging this. (It will change the interface of your etcdproxy-buildpack significantly.)

**Comment by tcdowney** [comment]
@drnic, regarding @sclevine's concern above. CAPI is going to be working on a story soon ([#166094919](https://www.pivotaltracker.com/story/show/166094919)) to propose an update to update the interface between Cloud Controller and the buildpacks to be sidecar-aware. I'd recommend waiting on that as well.

**Comment by drnic** [comment]
Closing for now. I was just trying to be helpful. Its not a critical addition.

**Pull request closed without merging**
